//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitCategories
    {
        public BenefitCategories()
        {
            this.Certificates = new HashSet<Certificates>();
            this.CitizenBenefits = new HashSet<CitizenBenefits>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public string LegalBasis { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Certificates> Certificates { get; set; }
        public virtual ICollection<CitizenBenefits> CitizenBenefits { get; set; }
    }
}
