//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificates
    {
        public int CertificateID { get; set; }
        public string CertificateNumber { get; set; }
        public int CitizenID { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public int IssuedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual BenefitCategories BenefitCategories { get; set; }
        public virtual Citizens Citizens { get; set; }
        public virtual Users Users { get; set; }
    }
}
