//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizens
    {
        public Citizens()
        {
            this.Certificates = new HashSet<Certificates>();
            this.CitizenBenefits = new HashSet<CitizenBenefits>();
            this.CitizenDocuments = new HashSet<CitizenDocuments>();
        }
    
        public int CitizenID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string SNILS { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ICollection<Certificates> Certificates { get; set; }
        public virtual ICollection<CitizenBenefits> CitizenBenefits { get; set; }
        public virtual ICollection<CitizenDocuments> CitizenDocuments { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
