//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenDocuments
    {
        public int DocumentID { get; set; }
        public int CitizenID { get; set; }
        public int DocTypeID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Citizens Citizens { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
    }
}
