//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTypes
    {
        public DocumentTypes()
        {
            this.CitizenDocuments = new HashSet<CitizenDocuments>();
        }
    
        public int DocTypeID { get; set; }
        public string DocTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CitizenDocuments> CitizenDocuments { get; set; }
    }
}
