//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EventType { get; set; }
        public string EventDescription { get; set; }
        public string EntityType { get; set; }
        public Nullable<int> EntityID { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
