//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BenefitsManagementSystemEntities : DbContext
    {
        public BenefitsManagementSystemEntities()
            : base("name=BenefitsManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BenefitCategories> BenefitCategories { get; set; }
        public DbSet<Certificates> Certificates { get; set; }
        public DbSet<CitizenBenefits> CitizenBenefits { get; set; }
        public DbSet<CitizenDocuments> CitizenDocuments { get; set; }
        public DbSet<Citizens> Citizens { get; set; }
        public DbSet<DocumentTypes> DocumentTypes { get; set; }
        public DbSet<EventLog> EventLog { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserRoles> UserRoles { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
