//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regions
    {
        public Regions()
        {
            this.Citizens = new HashSet<Citizens>();
        }
    
        public int RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> RegionCode { get; set; }
    
        public virtual ICollection<Citizens> Citizens { get; set; }
    }
}
