//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public UserRoles()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
