//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen_Benefits_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Certificates = new HashSet<Certificates>();
            this.CitizenBenefits = new HashSet<CitizenBenefits>();
            this.EventLog = new HashSet<EventLog>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Certificates> Certificates { get; set; }
        public virtual ICollection<CitizenBenefits> CitizenBenefits { get; set; }
        public virtual ICollection<EventLog> EventLog { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
